version: '3.8'

services:
  kiwi7:
    build:
      context: .
      dockerfile: Dockerfile
    image: kiwi7-img
    container_name: kiwi7-app
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8001:8001"
    volumes:
      - /home/kdy987/kiwi7:/kiwi7
    env_file:
      - .env.docker      
    # sqlite 사용시 별도 db 컨테이너 불필요
    # depends_on: []
    # command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
